root: true

parser: babel-eslint

extends:
  - airbnb
  - airbnb/hooks
  - plugin:prettier/recommended
  - prettier/react

env:
  browser: true

plugins:
  - simple-import-sort

rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  sort-imports: off
  import/order: off
  react/require-default-props:
    - error
    - ignoreFunctionalComponents: true
