backend:
  name: git-gateway
  # name: github
  # repo: alex-k1m/jamstack-blog
  # branch: master (default)

publish_mode: editorial_workflow # adds an interface for drafting, reviewing, and approving posts
media_folder: static/assets # specifies where uploaded files are saved in the repo
public_folder: assets # indicates where they are found in the published site
site_url: https://alexkim-jamstack-blog.netlify.app

collections:
  - name: blog # Used in routes
    label: Blog # Used in the UI
    folder: blog # where the documents are stored
    # media files being saved in the same directory as the entry and the image field being populated with the relative path to the image:
    extension: mdx
    format: frontmatter
    path: '{{slug}}/index'
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template
    # filter:
    # field: language
    # value: en
    fields: # The fields for each document, usually in front matter
      # label: Field label in the editor UI.
      # name: Field name in the document front matter.
      # widget: Determines UI style and value data type. See docs.
      # default (optional): Sets a default value for the field.
      - label: Publication date
        name: date
        widget: datetime
        dateFormat: DD.MM.YYYY
        timeFormat: HH:mm

      - label: Title
        name: title
        widget: string

      - label: Details
        name: details
        widget: object
        fields:
          - label: Featured image
            name: featuredImage
            widget: image
            allow_multiple: false

          - label: Tags
            name: tags
            widget: list

          - label: Rating
            name: rating
            widget: select
            options: [★, ★★, ★★★, ★★★★, ★★★★★]

          - label: Sponsored
            name: sponsored
            widget: boolean

          - label: Time to read
            name: timeToRead
            widget: number
            min: 1
            max: 60

      - label: Excerpt
        name: excerpt
        widget: text

      - label: Content
        name: body
        widget: markdown

      - label: Layout
        name: layout
        widget: hidden
        default: blog
